### ISSUE TITLE
Error when trying to build on linux

### ISSUE THREAD

**Issue by saileshkush95** [iPzard/electron-react-python-template#27]
I'm trying to build this project on linux system, running ubunut version 20.  
I used this command to build on linux

`yarn run build:package:linux`

But unfortunately it is not working
![Screenshot from 2021-08-04 11-30-49](https://user-images.githubusercontent.com/28560875/128128429-89553e7e-f744-4c9d-a623-b2b6f5535225.png)

**Comment by iPzard** [comment]
Thanks for reporting this! I don't currently have a Linux build available but can probably spin one up on VirtualBox sometime in the future in order to investigate this further. In the meantime.. I found some additional resources on this issue in Linux that might be helpful:

[Similar Issue](https://github.com/electron-userland/electron-forge/issues/709#issuecomment-469729158)
[Electron Packager Config](https://www.electronforge.io/configuration#packager-config)

**Comment by saileshkush95** [comment]
@iPzard thank you for help. I tried you suggestion but it won't works

**Comment by iPzard** [comment]
Thanks! I'll also try to get this working and report back here.

**Comment by iPzard** [comment]
@saileshkush95 FYI.. got my Linux environment all set up on Virtualbox, Ubuntu 20.xx.. have a busy week coming up, but will try to start hammering away at this next weekend now that my environment is ready, unless you beat me to it.

**Comment by oguzkaganeren** [comment]
I got same and I was able to build with `npx electron-packager .` on linux.

**Comment by kaka-lin** [comment]
Hi ,

This solution is works for me
https://github.com/electron-userland/electron-installer-debian/issues/175#issuecomment-486952647

**Comment by iPzard** [comment]
Thanks @kaka-lin! I've made some updates to the default project and the documentation in the PR linked below to help developers avoid further issues with packaging. 

https://github.com/iPzard/electron-react-python-template/pull/31
