### ISSUE TITLE
Getting dynamic import() error

### ISSUE THREAD

**Issue by birkanozer** [iPzard/electron-react-python-template#32]
**🦟 Describe the bug**<br />
Getting dynamic import() error

**Steps to Reproduce**<br />
1) Try to run package with node v17.3

**Error output**<be />

```
> myproject@1.0.0 start
> node ./scripts/dispatch start

/home/user/myproject/scripts/start.js:2
const getPort = require("get-port");
                ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/user/myproject/node_modules/get-port/index.js from /home/user/myproject/scripts/start.js not supported.
Instead change the require of index.js in /home/user/myproject/scripts/start.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/user/myproject/scripts/start.js:2:17)
    at Object.<anonymous> (/home/user/myproject/scripts/dispatch.js:8:21) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v17.3.0
```

**Expected behavior**<br />

**Additional context**<br />
I changed all require("") to import but still getting errors

Edit: Added error code

**Comment by birkanozer** [comment]
Hi again, 
After some digging up, I found that "get-ports" package converted to the ESM version. Since Electron is not ESM compatible yet these 2 packages are conflicting. I tried to update the whole package to ESM compatible but failed. It still throws some errors. Maybe it's because I use WSL rather than bare metal hw. Anyway I created a pull request. Can you check it and fix the version issue?
Thanks

https://github.com/iPzard/electron-react-python-template/pull/33

**Comment by iPzard** [comment]
I really appreciate the initiative on this! What are your thoughts if I update the `get-ports` package to a pre-ESM version until Electron is up to speed?

**Comment by iPzard** [comment]
Had a chance to look into this.. looks like this project [uses version `^5.1.1` of `get-port`](https://github.com/iPzard/electron-react-python-template/blob/bb1ef1fb40a9c5a3845b465725762d4016f39215/package.json#L8), which is already a pre-ESM version.. since `get-port` wasn't [updated to use ESM](https://github.com/sindresorhus/get-port/commit/c08a4ae8935e8fdc2c261b4e0024fd71a6dc6516) until version 6.

From what I see [in the PR](https://github.com/iPzard/electron-react-python-template/pull/33/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519), it looks like the `get-port` package has been updated to use version 6.0+ in the environment you're running into this error. It may be best to just downgrade that until Electron is also ready.

Will close this ticket since this doesn't appear to be an issue here with this template project.
