### ISSUE TITLE
Not run python part after build in Windows

### ISSUE THREAD

**Issue by alejandrocortell** [iPzard/electron-react-python-template#54]
Hi all, I'm using the app in Windows and I'm trying to create a package for windows.
I have pyinstaller installed and filled the environment variables. Also Wix installed and configured.
When I run the command `build:package:windows` I don't have any error in the terminal and say that the package has been created correctly.

The issue is when I run the .exe created in dist/windows/app-win32-x64 or when I install the app with the .msi created, I have this error

![Captura de pantalla_20221218_220317](https://user-images.githubusercontent.com/66571325/208319352-1f88da4f-9107-436f-ba57-dd17a1dc674a.png)

Any idea to solve the issue?

Thanks

**Comment by sinthoras50** [comment]
@alejandrocortell Hi, not sure if you solved it already but I found a dirty workaround that seemingly makes it work for me. The problem seems to come from a python Click library which flask uses to echo messages to the console. It seems to cause this error when the console is hidden (like when the application is built). 

Adding a None check for file in site-packages/click/utils.py in the echo function fixed it for me. 
![image](https://user-images.githubusercontent.com/37308362/216499282-ffb1b805-3551-491d-a890-962e0a17ca3c.png)
